name: Build
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPDATE_SITE_TOKEN: ${{ secrets.UPDATE_SITE_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Create tar file
      run: |
        tar -czvf shell-integration.tar.gz \
          shell/ \
          tools/install_utils.sh \
          fig.sh
    - name: Update Site
      run: |
        git clone https://withfig-bot:$UPDATE_SITE_TOKEN@github.com/withfig/public-site-nextjs
        cd public-site-nextjs

        cp shell-integration.tar.gz tools/install-shell-integration.sh public/
      
        git config user.email "hello@withfig.com"
        git config user.name "Figbot"
        
        git add .
        git commit -m "Updated shell integration script"
        git push origin main
